---
- name: "Deploy application"
  become: yes
  hosts: prod
  tasks:
    - name: Removing a file
      file:
        path: /usr/share/nginx/html
        state: absent
    - name: Create Folder
      file:
        path: /usr/share/nginx/html/
        state: directory
    - name: "Copy index.html"
      copy:
        content: "Salut séverine"
        dest: /usr/share/nginx/html/index.html
... 
