---
- name: "Install webapp-v3"
  become: yes
  hosts: prod
  tasks:
    - name: "Generate html"
      Template:
        src: templates/index.html.j2
        dest: /usr/share/nginx/html/index.html
---
        
